<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="admin_view_user.aspx.cs" Inherits="LetsAdopt.admin_view_user" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>All Users</title>
    <link href="css/gridview.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">
    <link href="master.css" rel="stylesheet" type="text/css" />
    <link href="css/gridview.css" rel="stylesheet" />
    <link href="css/contact.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div style="width: 100%;margin-top:-2%">
            <h2 style="margin-left:45%;margin-bottom:5px">All Users</h2>
            <asp:Button ID="Button1" runat="server" Text="View Posts" class="btn btn-primary" OnClick="Button1_Click"/>
            <asp:GridView ID="GridView1" runat="server" CssClass="table table-condensed table-hover"
               ShowHeaderWhenEmpty="True"
               AutoGenerateDeleteButton="True"
                AutoGenerateColumns="True"
                DataKeyNames="name"
                OnRowDeleting="GridView1_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="name" HeaderText="Name" />
                </Columns>




            </asp:GridView>
        </div>
    </form>
</body>
</html>
