<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="LetsAdopt.Admin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Admin Panel</title>

    <link href="css/gridview.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">
    <link href="master.css" rel="stylesheet" type="text/css" />
    <link href="css/gridview.css" rel="stylesheet" />
    <link href="css/contact.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">

        <div style="width: 100%;margin-top:-2%">
            <h2 style="margin-left:45%;margin-bottom:5px">All Posts</h2>
            <asp:Button ID="Button1" runat="server" Text="View Users" class="btn btn-primary" OnClick="Button1_Click"/>
            <asp:GridView ID="GridView1" runat="server" CssClass="table table-condensed table-hover"
                ShowHeaderWhenEmpty="True"
                DataKeyNames="pid"
                AutoGenerateColumns="false"
                AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting">
                <Columns>

                    <asp:TemplateField HeaderText="Image">
                        <ItemTemplate>
                            <asp:Image ID="Image1" runat="server" Height="150px" Width="150px"
                                ImageUrl='<%#Eval("image") %>' />
                        </ItemTemplate>

                    </asp:TemplateField>
                    <asp:BoundField HeaderText="Description" DataField="des" />
                    <asp:BoundField HeaderText="Post ID" DataField="pid" />
                </Columns>
            </asp:GridView>

        </div>
        <div style="height: 100px;">
        </div>
        <footer class="footer">
            <div class="container">
                <p style="margin-top: 20px; color: gray"><i class="fa fa-copyright" aria-hidden="true"></i>2020 Let's Adopt</p>
            </div>

        </footer>
    </form>

</body>
</html>
