<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="MyPost.aspx.cs" Inherits="LetsAdopt.MyPost" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="margin-left: 35%">
        <h2 style="margin-top: 5%; margin-left: 15%">My Posts</h2>
        <asp:Image ID="Image2" runat="server" Height="400px" Width="600px" />
    </div>
    <asp:GridView ID="GridView1" runat="server" CssClass="table table-condensed table-hover" ShowHeaderWhenEmpty="True"
        AutoGenerateColumns="false"
        DataKeyNames="pid"
        OnRowDeleting="OnRowDeleting"
        AutoGenerateDeleteButton="true">
        <Columns>
            <asp:BoundField DataField="pid" HeaderText="Post ID" />

            <asp:TemplateField HeaderText="Image">
                <ItemTemplate>
                    <asp:Image ID="Image1" runat="server" Height="150px" Width="150px"
                        ImageUrl='<%#Eval("image") %>' />
                </ItemTemplate>

            </asp:TemplateField>
            <asp:BoundField DataField="des" HeaderText="Description" />
        </Columns>
        <EmptyDataTemplate>
            <div>You Have not posted anything yet</div>
        </EmptyDataTemplate>
    </asp:GridView>
    <div style="height: 100px;">
    </div>
</asp:Content>
